spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  rabbitmq:
      host: localhost
      port: 5679
      username: ${RABBIT_USERNAME}
      password: ${RABBIT_PASSWORD}

  datasource:
    url: jdbc:postgresql://localhost:5432/skt-task
    username: jxjxjxm
    password: JJJM214332

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect

server:
  port: 9093
rabbit-names-config:
  products-exchange-name: productExchange
  receive-products-queue-name: receiveProductsQueue
  request-products-queue-name: requestProductsQueue
  store-products-queue-name: storeProductsQueue
  store-reply-products-queue-name: storeReplyProductsQueue

  reply-products-routing-key: reply.products
  request-products-routing-key: request.products
  store-products-routing-key: store.product
  store-reply-products-routing-key: store.reply.product