spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skt-task
    username: jxjxjxm
    password: JJJM214332
    generate-dll: true
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
        host: localhost
        port: 5679
        username: ${RABBIT_USERNAME}
        password: ${RABBIT_PASSWORD}
server:
  port: 8080
rabbit-names-config:
  products-exchange-name: productExchange
  receive-products-queue-name: receiveProductsQueue
  request-products-queue-name: requestProductsQueue
  store-products-queue-name: storeProductsQueue
  store-reply-products-queue-name: storeReplyProductsQueue

  reply-products-routing-key: reply.products
  request-products-routing-key: request.products
  store-products-routing-key: store.product
  store-reply-products-routing-key: store.reply.product